### ISSUE TITLE
Outgoing group text is not received by recepients

### ISSUE THREAD

**Issue by cimbalom** [qklabs/qksms-tracker#29] opened 2015-02-27 17:12 UTC
I sent a group text to 5 people, just plain text telling them about something. They reported receiving a blank image frame that they couldn't open and nothing else. I use a Nexus 5 on the Koodo network in Canada..

**Comment by srcreigh** [comment] 2015-02-27 17:15
Thanks for reporting @cimbalom! Can you check if you have the "Group messaging" option checked in Settings?

**Comment by cimbalom** [comment] 2015-02-27 17:17
Hi,
Yes! Perhaps I should deselect it if I just want to send several people the same message. Thanks.
Dan

**Comment by srcreigh** [comment] 2015-02-27 17:19
"Group messaging" will cause QKSMS to try and create fancy MMS messages (like email with a bunch of cc's, basically). It's fun but at this point less reliable than just plain old sending a bunch of people a text message.

Let me know if that solves your issue!

**Comment by cimbalom** [comment] 2015-02-27 17:43
I deselected Group Messaging and sent out another message. I didn't hear back so I tried contacting one of them by another means, they said they didn't get anything at all this time.

**Comment by cimbalom** [comment] 2015-02-27 17:50
Hmm actually they did get it after about a 20min delay, but it was an MMS, not a regular SMS.

**Comment by cimbalom** [comment] 2015-02-27 17:52
And I received a blank message from "Null" at the same time as one of them replied.. strange... I might just avoid group messaging altogether for the moment..

**Comment by srcreigh** [comment] 2015-03-19 03:42
I'm going to close this because it isn't clear what the issue is, but feel free to open it up with specific issues. I.e. "when Group Messaging it is supposed to send as SMS messages but it sends as MMS" etc.

**Closed by srcreigh** 2015-03-19 03:42 UTC
